services:
  framework-web-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: benjamin
        UID: 1000
        MAIL: benjamin.perez@univ-orleans.fr
        NAME: "Benjamin Perez"
    container_name: container-projet-SI 
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
    - .:/var/www/html
    ports:
    - "8000:8000"
    - "8020:4200"
    environment:
      PHP_IDE_CONFIG: serverName=contacts
      PS1: "[ $$(whoami) | $$(pwd) ] "
