services:
  framework-web-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: bidule # À Modifier
        UID: 501         # À Modifier
        MAIL: bidule@univ-orleans.fr # À Modifier
        NAME: "Machin Bidule"        # À Modifier
    container_name: container-fw2-tp-bidule # À Modifier
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
    - .:/var/www/html
    ports:
    - "8000:8000"
    - "8020:4200"
    environment:
      PHP_IDE_CONFIG: serverName=contacts
      PS1: "[ $$(whoami) | $$(pwd) ] "
