services:
  framework-web-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: matis
        UID: 1000
        MAIL: matis.gasse@etu.univ-orleans.fr
        NAME: "Matis Gasse"
    container_name: container-projet-SI 
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
      - "8020:4200"
    environment:
      PHP_IDE_CONFIG: serverName=contacts
      PS1: "[ $$(whoami) | $$(pwd) ] "
      DATABASE_URL: "postgresql://postgres:postgres@postgres_db:5432/projetsi"
    depends_on:
      - postgres_db
    networks:
      - my_network  # 🔥 Ajout de Symfony au réseau du BAAS

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projetsi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - my_network  # 🔥 Ajout de PostgreSQL au même réseau (optionnel)

volumes:
  postgres_data:

networks:
  my_network:
    external: true  # 🔥 On indique que le réseau est déjà existant
